<!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $this->Title; ?></title>
		<meta name="author" content="Tom Flídr <tomflidr(at)gmail(dot)com>" />
		<link rel="shortcut icon" href="<?php echo $this->Url('Assets::Img', array('path'=>'/static/img/favicon.ico')); ?>" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<?php echo $this->Css('fixedHead')->Render(); ?>
		<?php echo $this->Js('fixedHead')->Render(); ?>
	</head>
	<body>
		<!--[if lt IE 9]><div class="filters"><![endif]-->
		<!--[if (gt IE 8)|!(IE)]><!--><div class="no-filters">
			<!--<![endif]-->
			<div class="master-container">
				<form class="logout"
					action="<?php echo $this->Url("Default::Logout"); ?>"
					method="POST"
					enctype="application/x-www-form-urlencoded">
					<?php if ($this->User): ?>
							<input type="hidden" name="csrf" value="<?php echo App_Controllers_Base::GetSessionHash(); ?>" />
							<span><?php echo $this->User->FullName; ?></span>
							<input class="text-link" type="submit" value="Logout" />
					<?php endif; ?>
				</form>
				<div class="content">
					<?php echo $this->GetContent(); ?>
				</div>
			</div>
		</div>
	</body>
	<?php echo $this->Js('varFoot')->Render(); ?>
</html>