<?php

/**
 * Debugger bluescreen template.
 *
 * This file is part of the Nette Framework.
 * Copyright (c) 2004, 2010 David Grudl (http://davidgrudl.com)
 *
 * @param      array     $exception
 * @param      Nette\Application\Application $application
 * @return     void
 */

//namespace Nette;

//use Nette;



/**
 * Page title.
 */
static $errorTypes = array(
	E_ERROR => 'Fatal Error',
	E_USER_ERROR => 'User Error',
	E_RECOVERABLE_ERROR => 'Recoverable Error',
	E_CORE_ERROR => 'Core Error',
	E_COMPILE_ERROR => 'Compile Error',
	E_PARSE => 'Parse Error',
	E_WARNING => 'Warning',
	E_CORE_WARNING => 'Core Warning',
	E_COMPILE_WARNING => 'Compile Warning',
	E_USER_WARNING => 'User Warning',
	E_NOTICE => 'Notice',
	E_USER_NOTICE => 'User Notice',
	E_STRICT => 'Strict',
	E_DEPRECATED => 'Deprecated',
	E_USER_DEPRECATED => 'User Deprecated',
);

$title = ($exception instanceof \FatalErrorException && isset($errorTypes[$exception->getSeverity()])) ? $errorTypes[$exception->getSeverity()] : get_class($exception);

//$expandPath = NETTE_DIR . DIRECTORY_SEPARATOR; // . 'Utils' . DIRECTORY_SEPARATOR . 'Object';
$expandPath = __DIR__ . '\..\..' . DIRECTORY_SEPARATOR; // . 'Utils' . DIRECTORY_SEPARATOR . 'Object';

$counter = 0;

if (headers_sent()) {
	echo '</pre></xmp></table>';
}
echo '<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="robots" content="noindex,noarchive">
	<meta name="generator" content="Nette Framework">
	<title>' . htmlspecialchars($title) . '</title><!-- ';
		$ex = $exception; echo $ex->getMessage(), ($ex->getCode() ? ' #' . $ex->getCode() : '');
		while ((method_exists($ex, 'getPrevious') && $ex = $ex->getPrevious()) || (isset($ex->previous) && $ex = $ex->previous)) echo '; caused by ', get_class($ex), ' ', $ex->getMessage(), ($ex->getCode() ? ' #' . $ex->getCode() : '');
	echo ' -->
	<style type="text/css" class="nette">
    body{margin:0 0 2em;padding:0}
	#netteBluescreen{font:9pt/1.5 Verdana,sans-serif;background:white;color:#333;position:absolute;left:0;top:0;width:100%;z-index:23178;text-align:left}
	#netteBluescreen *{font:inherit;color:inherit;background:transparent;border:none;margin:0;padding:0;text-align:inherit;text-indent:0}
	#netteBluescreen b{font-weight:bold}
	#netteBluescreen i{font-style:italic}
	#netteBluescreenIcon{position:absolute;right:.5em;top:.5em;z-index:23179;text-decoration:none;background:#CD1818;padding:3px}
	#netteBluescreenError{background:#CD1818;color:white;font:13pt/1.5 Verdana,sans-serif!important;display:block}
	#netteBluescreen h1{font-size:18pt;font-weight:normal;text-shadow:1px 1px 0 rgba(0,0,0,.4);margin:.7em 0}
	#netteBluescreen h2{font:14pt/1.5 sans-serif!important;color:#888;margin:.6em 0}
	#netteBluescreen a{text-decoration:none;color:#328ADC;padding:2px 4px;margin:-2px -4px}
	#netteBluescreen a abbr{font-family:sans-serif;color:#BBB}
	#netteBluescreen h3{font:bold 10pt/1.5 Verdana,sans-serif!important;margin:1em 0;padding:0}
	#netteBluescreen p,
	#netteBluescreen pre{margin:.8em 0}
	#netteBluescreen pre,
	#netteBluescreen code,
	#netteBluescreen table{font:9pt/1.5 Consolas,monospace!important}
	#netteBluescreen pre,
	#netteBluescreen table{background:#FDF5CE;padding:.4em .7em;border:1px dotted silver;overflow:auto}
	#netteBluescreen table pre{padding:0;margin:0;border:none}
	#netteBluescreen pre.nette-dump span{color:#C22}
	#netteBluescreen pre.nette-dump a{color:#333}
	#netteBluescreen div.panel{padding:1px 25px}
	#netteBluescreen div.inner{background:#F4F3F1;padding:.1em 1em 1em;border-radius:8px;-moz-border-radius:8px;-webkit-border-radius:8px}
	#netteBluescreen table{border-collapse:collapse;width:100%}
	#netteBluescreen .outer{overflow:auto}
	#netteBluescreen td,
	#netteBluescreen th{vertical-align:top;text-align:left;padding:2px 6px;border:1px solid #e6dfbf}
	#netteBluescreen th{width:10%;font-weight:bold}
	#netteBluescreen tr:nth-child(2n),
	#netteBluescreen tr:nth-child(2n) pre{background-color:#F7F0CB}
	#netteBluescreen ol{margin:1em 0;padding-left:2.5em}
	#netteBluescreen ul{font:7pt/1.5 Verdana,sans-serif!important;padding:2em 4em;margin:1em 0 0;color:#777;background:#F6F5F3;border-top:1px solid #DDD}
	#netteBluescreen .highlight{background:#CD1818;color:white;font-weight:bold;font-style:normal;display:block;padding:0.4em;margin:0 -.4em}
	#netteBluescreen .line{color:#9F9C7F;font-weight:normal;font-style:normal}
	#netteBluescreen a[href^=editor\:]{color:inherit;border-bottom:1px dotted #328ADC}
</style>
</head>
<body>
<div id="netteBluescreen">
	<a id="netteBluescreenIcon" href="#" rel="next"><abbr>&#x25bc;</abbr></a
	><div>
		<div id="netteBluescreenError" class="panel">
			<h1>' . htmlspecialchars($title), ($exception->getCode() ? ' #' . $exception->getCode() : '') . '</h1>
			<p>' . htmlspecialchars($exception->getMessage()) . '</p>
		</div>';
		$ex = $exception; $level = 0;
		do {
			if ($level++):
				echo '<div class="panel">
					<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Caused by <abbr>' . (($collapsed = $level > 2) ? '&#x25ba;' : '&#x25bc;') . '</abbr></a></h2>
					<div id="netteBsPnl' . $counter . '" class="' . ($collapsed ? 'nette-collapsed ' : '') . 'inner">
						<div class="panel">
							<h1>' . htmlspecialchars(get_class($ex)), ($ex->getCode() ? ' #' . $ex->getCode() : '') . '</h1>
							<p><b>' . htmlspecialchars($ex->getMessage()) . '</b></p>
						</div>';
			endif;

			$stack = $ex->getTrace();
			$expanded = NULL;
			if (strpos($ex->getFile(), $expandPath) === 0) {
				foreach ($stack as $key => $row) {
					if (isset($row['file']) && strpos($row['file'], $expandPath) !== 0) { $expanded = $key; break; }
				}
			}
			if (is_file($ex->getFile())):
				echo '<div class="panel">
					<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Source file <abbr>' . (($collapsed = $expanded !== NULL) ? '&#x25ba;' : '&#x25bc;') . '</abbr></a></h2>
					<div id="netteBsPnlp' . $counter . '" class="' . ($collapsed ? 'nette-collapsed ' : '')  .'inner">
						<p><b>Fi' . 'le:</b> ' . ((Debug::$editor) ? '<a href="' . htmlspecialchars(DebugHelpers::editorLink($ex->getFile(), $ex->getLine())) . '">' : '') . htmlspecialchars($ex->getFile()) . (Debug::$editor ? '</a>':'') . '&nbsp; <b>Line:</b> ' . $ex->getLine() . '</p>
						<pre>' . DebugHelpers::highlightFile($ex->getFile(), $ex->getLine()) . '</pre>
					</div>
				</div>';
			endif;


			if (isset($stack[0]['class']) && $stack[0]['class'] === 'Nette\Debug' && ($stack[0]['function'] === '_shutdownHandler' || $stack[0]['function'] === '_errorHandler')) unset($stack[0]);
			if (Debug::$fatalErrorDebugBackTrace) $stack = Debug::$fatalErrorDebugBackTrace;
			if ($stack):
				echo '<div class="panel">';
					echo '<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Call stack <abbr>&#x25bc;</abbr></a></h2>';
					echo '<div id="netteBsPnl' . $counter . '" class="inner">';
						echo '<ol>';
							foreach ($stack as $key => $row):
								echo '<li>';
									echo '<p>';
										if (isset($row['file']) && is_file($row['file'])):
											echo Debug::$editor ? '<a href="' . htmlspecialchars(DebugHelpers::editorLink($row['file'], $row['line'])) . '"' : '<span';
											echo ' title="' . htmlSpecialChars($row['file']) . '">';
												echo htmlSpecialChars(basename(dirname($row['file'])));
												echo '/<b>', htmlSpecialChars(basename($row['file'])), '</b>';
											echo Debug::$editor ? '</a>':'</span>';
											echo ' (' . $row['line'] . ')';
										else:
											echo '<i>inner-code</i>'; if (isset($row['line'])) echo ' (', $row['line'], ')';
										endif;

										if (isset($row['file']) && is_file($row['file'])): 
											echo '<a href="#" rel="netteBsSrc';
											echo $level."-".$key;
											echo '">&nbsp;source <abbr>&#x25ba;</abbr></a>&nbsp; "';
										endif;

										if (isset($row['class'])) echo $row['class'] . $row['type'];
										echo $row['function'];
										
										echo '(';
										if (!empty($row['args'])):
											echo '<a href="#" rel="netteBsArgs'.$level."-".$key.'">arguments <abbr>&#x25ba;</abbr></a>';
										endif;
										echo ')';
									echo '</p>';

									if (!empty($row['args'])):
										echo '<div class="nette-collapsed outer" id="netteBsArgs' . $level . "-" . $key; echo '"><table>';
										try {
											$r = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
											$params = $r->getParameters();
										} catch (\Exception $e) {
											$params = array();
										}
										foreach ($row['args'] as $k => $v) {
											echo '<tr><th>', (isset($params[$k]) ? '$' . $params[$k]->name : "#$k"), '</th><td>';
											echo DebugHelpers::clickableDump($v);
											echo "</td></tr>\n";
										}
										echo '</table>
										</div>';
									endif;

									if (isset($row['file']) && is_file($row['file'])):
										echo '<pre '; if ($expanded !== $key) echo 'class="nette-collapsed"'; echo ' id="netteBsSrc'; echo $level.'-'.$key; echo '">';echo DebugHelpers::highlightFile($row['file'], $row['line']); echo '</pre>';
									endif;
									
								echo '</li>';
							endforeach;
						echo '</ol>';
					echo '</div>';
				echo '</div>';
			endif;



			if ($ex instanceof IDebugPanel && ($tab = $ex->getTab()) && ($panel = $ex->getPanel())):
				echo '<div class="panel">
						<h2><a href="#" rel="netteBsPnl' . ++$counter . '">' . htmlSpecialChars($tab) . ' <abbr>&#x25bc;</abbr></a></h2>

					<div id="netteBsPnl' . $counter . '" class="inner">
						' . $panel . '
					</div>
				</div>';
			endif;



			if (isset($ex->context) && is_array($ex->context)):
				echo '<div class="panel">
					<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Variables <abbr>&#x25ba;</abbr></a></h2>

					<div id="netteBsPnl' . $counter . '" class="nette-collapsed inner">
						<div class="outer">
							<table>';
				foreach ($ex->context as $k => $v) {
					echo '<tr><th>$', htmlspecialchars($k), '</th><td>', DebugHelpers::clickableDump($v), "</td></tr>\n";
				}
						echo '</table>
						</div>
					</div>
				</div>';
			endif;

		} while ((method_exists($ex, 'getPrevious') && $ex = $ex->getPrevious()) || (isset($ex->previous) && $ex = $ex->previous));
		
		while (--$level) echo '</div></div>';



		if (!empty($application)):
			echo '<div class="panel">
				<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Nette Application <abbr>&#x25ba;</abbr></a></h2>

				<div id="netteBsPnl' . $counter . '" class="nette-collapsed inner">
					<h3>Requests</h3>
					' . DebugHelpers::clickableDump($application->getRequests()) . '
					<h3>Presenter</h3>
					' . DebugHelpers::clickableDump($application->getPresenter()) . '
				</div>
			</div>';
		endif;



		echo '<div class="panel">
			<h2><a href="#" rel="netteBsPnl' . ++$counter . '">Environment <abbr>&#x25ba;</abbr></a></h2>
			<div id="netteBsPnl' . $counter . '" class="nette-collapsed inner">';
			
		$list = get_defined_constants(TRUE);
		if (!empty($list['user'])):
			echo '<h3><a href="#" rel="netteBsPnl-env-const">Constants <abbr>&#x25bc;</abbr></a></h3>
				<div class="outer">
					<table id="netteBsPnl-env-const">';
			foreach ($list['user'] as $k => $v) {
				echo '<tr><th>', htmlspecialchars($k), '</th>';
				echo '<td>', DebugHelpers::clickableDump($v), "</td></tr>\n";
			}
			echo '</table>
				</div>';
		endif;


		echo '<h3><a href="#" rel="netteBsPnl-env-files">Included files <abbr>&#x25ba;</abbr></a> (' . count(get_included_files()) . ')</h3>
			<div class="outer">
				<table id="netteBsPnl-env-files" class="nette-collapsed">';
		foreach (get_included_files() as $v) {
			echo '<tr><td>', htmlspecialchars($v), "</td></tr>\n";
		}
		echo '</table>
		</div>';


		echo '<h3>$_SERVER</h3>';
		if (empty($_SERVER)):
			echo '<p><i>empty</i></p>';
		else:
			echo '<div class="outer">
				<table>';			
			foreach ($_SERVER as $k => $v):
				echo '<tr><th>', htmlspecialchars($k), '</th><td>', DebugHelpers::clickableDump($v), "</td></tr>\n";
			endforeach;
			echo '</table>
			</div>';
		endif;
		echo '</div></div>';



		echo '<div class="panel">
			<h2><a href="#" rel="netteBsPnl' . ++$counter . '">HTTP request <abbr>&#x25ba;</abbr></a></h2>

			<div id="netteBsPnl' . $counter . '" class="nette-collapsed inner">';
		if (function_exists('apache_request_headers')):
			echo '<h3>Headers</h3>
				<div class="outer">
					<table>';
			foreach (apache_request_headers() as $k => $v):
				echo '<tr><th>', htmlspecialchars($k), '</th><td>', htmlspecialchars($v), "</td></tr>\n";
			endforeach;
			echo '</table>
			</div>';
		endif;


		foreach (array('_GET', '_POST', '_COOKIE') as $name):
			echo '<h3>$' . $name . '</h3>';
			if (empty($GLOBALS[$name])):
				echo '<p><i>empty</i></p>';
			else:
				echo '<div class="outer">
					<table>';
				foreach ($GLOBALS[$name] as $k => $v):
					echo '<tr><th>', htmlspecialchars($k), '</th><td>', DebugHelpers::clickableDump($v), "</td></tr>\n";
				endforeach;
				echo '</table>
				</div>';
			endif;
		endforeach;
		echo '</div></div>';



		echo '<div class="panel">
			<h2><a href="#" rel="netteBsPnl' . ++$counter . '">HTTP response <abbr>&#x25ba;</abbr></a></h2>';

		echo '<div id="netteBsPnl' . $counter . '" class="nette-collapsed inner">
			<h3>Headers</h3>';
		if (headers_list()):
			echo '<pre>';
			foreach (headers_list() as $s):
				echo htmlspecialchars($s), '<br>';
			endforeach;
			echo '</pre>';
		else:
			echo '<p><i>no headers</i></p>';
		endif;
		echo '</div></div>';


		echo '<ul>
			<li>Report generated at ' . @date('Y/m/d H:i:s', Debug::$time) . '</li>';
			if (preg_match('#^https?://#', Debug::$source)):
				echo '<li><a href="', htmlSpecialChars(Debug::$source), '">', htmlSpecialChars(Debug::$source), '</a></li>';
			elseif (Debug::$source):
				echo '<li>', htmlSpecialChars(Debug::$source), '</li>';
			endif;
			echo '<li>PHP ', htmlSpecialChars(PHP_VERSION), '</li>';
			if (isset($_SERVER['SERVER_SOFTWARE'])):
				echo '<li>', htmlSpecialChars($_SERVER['SERVER_SOFTWARE']), '</li>';
			endif;
		echo '</ul>
	</div>
</div>';

echo '<script type="text/javascript">/*<![CDATA[*/var bs=document.getElementById("netteBluescreen");document.body.appendChild(bs);document.onkeyup=function(b){b=b||window.event;b.keyCode==27&&bs.onclick({target:document.getElementById("netteBluescreenIcon")})};
for(var i=0,styles=document.styleSheets;i<styles.length;i++)if((styles[i].owningElement||styles[i].ownerNode).className!=="nette"){styles[i].oldDisabled=styles[i].disabled;styles[i].disabled=true}else styles[i].addRule?styles[i].addRule(".nette-collapsed","display: none"):styles[i].insertRule(".nette-collapsed { display: none }",0);
bs.onclick=function(b){b=b||window.event;for(var a=b.target||b.srcElement;a&&a.tagName&&a.tagName.toLowerCase()!=="a";)a=a.parentNode;if(!a||!a.rel)return true;for(var d=a.getElementsByTagName("abbr")[0],c=a.rel==="next"?a.nextSibling:document.getElementById(a.rel);c.nodeType!==1;)c=c.nextSibling;b=c.currentStyle?c.currentStyle.display=="none":getComputedStyle(c,null).display=="none";try{d.innerHTML=String.fromCharCode(b?9660:9658)}catch(e){}c.style.display=b?c.tagName.toLowerCase()==="code"?"inline":
"block":"none";if(a.id==="netteBluescreenIcon"){a=0;for(d=document.styleSheets;a<d.length;a++)if((d[a].owningElement||d[a].ownerNode).className!=="nette")d[a].disabled=b?true:d[a].oldDisabled}return false};/*]]>*/</script>
</body>
</html>';