<?php /** @var $this \MvcCore\View */ ?>
<?php /** @var $this->SignOutForm \MvcCore\Ext\Auth\SignOutForm */ ?>

<?php if ($this->SignOutForm): ?>
	<?php echo $this->SignOutForm->RenderBegin(); ?>

		<?php if ($this->User): ?>
			<span><?php echo $this->User->GetFullName(); ?></span>
		<?php endif; ?>

		<?php foreach ($this->SignOutForm->Fields as & $field): ?>
			<?php echo $field->Render(); ?>
		<?php endforeach; ?>

	<?php echo $this->SignOutForm->RenderEnd(); ?>
<?php endif; ?>
